// /lib/genreMap.js

export const parentGenreMap = {
  "pop": [
    "pastel", "bubblegum", "bright", "youthful", "vibrant", "optimistic",
    "modern fashion", "high fashion", "street style", "sleek", "trendy", "chic",
    "sunshine", "golden hour", "beach", "poolside", "festival", "summer",
    "bedroom lights", "string lights", "fairy lights", "neon glow", "cozy light", "moody light",
    "glossy", "polished", "reflective", "shimmer", "metallic", "glamorous",
    "choreography", "dance", "performance", "stage", "energetic", "idol",
    "digital", "flawless", "aspirational", "commercial", "curated", "crisp"
  ],
  "indie": [
    "vintage", "retro", "sepia", "film grain", "nostalgia", "analog", "old school",
    "polaroid", "candid", "imperfect", "authentic", "unfiltered", "spontaneous",
    "thrift", "oversized", "upcycled", "eclectic", "boho", "sustainable",
    "lo-fi", "light leaks", "muted colors", "grainy", "hazy", "chill", "raw",
    "alt", "quirky", "subtle", "understated", "unconventional", "dreamy",
    "natural light", "portraits", "raw emotion", "unposed", "moody", "real life",
    "suburban", "contemplation", "backyard", "downtempo", "introspective", "solitude",
    "artisan", "handmade", "natural textures", "earthy", "minimalist", "rustic", "organic"
  ],
  "rap": [
    "urban", "cityscape", "concrete", "street", "gritty", "industrial", "inner city",
    "streetwear", "hoodies", "sneakers", "athletic", "designer", "drip", "street style",
    "dark shadows", "desaturated", "raw", "unfiltered", "documentary", "realism", "rough",
    "graffiti", "mural", "street art", "rebel art", "urban art", "wall art",
    "trap lights", "red neon", "blue neon", "smoky", "low-key", "club haze", "late night",
    "fast cars", "luxury cars", "custom cars", "speed", "power", "exotic",
    "money", "bling", "diamond", "gold chain", "cash", "wealth", "flex",
    "confident", "swagger", "assertive", "dominant", "boss", "street cred"
  ],
  "hip hop": [
    "hypebeast", "exclusive", "limited edition", "logomania", "fresh kicks", "street couture",
    "skyline", "rooftop", "night lights", "metropolitan", "aspirational", "urban elegance",
    "monochrome", "black and white", "greyscale", "bold color", "sleek", "sophisticated",
    "gold chain", "iced out", "grills", "statement jewelry", "diamond", "opulent", "bling",
    "neon", "vibrant lights", "futuristic", "club lights", "energetic", "electric", "nightlife",
    "luxury interior", "mansion", "private jet", "yacht", "high-end club", "velvet", "polished",
    "squad", "group", "crew", "unity", "celebration", "party", "community", "team",
    "bold type", "graphic", "album art", "clean lines", "modern aesthetic", "street art inspired"
  ],
  "rock": [
    "leather jacket", "biker", "worn", "distressed", "rebel", "gritty", "punk", "rocker",
    "black and white", "stark", "shadows", "dramatic light", "raw intensity", "timeless",
    "loud", "energetic", "instruments", "sweat", "raw emotion", "unleashed", "headbanging",
    "grunge", "flannel", "ripped jeans", "band tee", "messy hair", "anti-fashion", "disheveled",
    "concert", "stage lights", "crowd", "live show", "music festival", "on stage",
    "vintage guitars", "classic instruments", "worn drums", "analog", "road worn", "old school",
    "rebel icons", "skulls", "chains", "band logos", "anti-establishment", "anarchy", "protest",
    "dark bar", "smoky", "dive bar", "backstage", "grimy", "underground", "rock club"
  ],
  "metal": [
    "dark fantasy", "demonic", "mythological", "gothic", "sorcery", "epic battle", "apocalyptic",
    "fire", "pyrotechnics", "flames", "burning", "volcanic", "destruction", "inferno",
    "skulls", "bones", "skeletal", "occult", "pentagram", "runes", "macabre",
    "spikes", "studs", "sharp", "chainmail", "armor", "aggressive", "intimidating",
    "black metal art", "dark forest", "winter", "corpse paint", "viking", "pagan", "grim",
    "dramatic light", "chiaroscuro", "shadow play", "smoke", "fog", "eerie", "ominous",
    "extreme close-up", "intense expressions", "screaming", "furious", "shredding", "raw power",
    "post-apocalyptic", "wasteland", "ruined city", "cyber-gothic", "dystopian"
  ],
  "grunge": [
    "emo", "melancholy", "angst", "introverted", "vulnerable", "sadcore", "moody",
    "film grain", "lo-fi", "unpolished", "natural flaws", "analog", "gritty", "vintage film",
    "messy hair", "bed head", "tousled", "unfussy", "disheveled", "effortless",
    "flannel", "distressed denim", "band tees", "ripped", "slouchy", "layered", "90s grunge",
    "distorted", "blurry", "out-of-focus", "fuzzy", "visual noise", "jarring", "unsettling",
    "dirty mirror", "messy room", "clutter", "urban decay", "abandoned", "rebellious setting",
    "faded colors", "desaturated", "muted tones", "drab hues", "somber", "overcast",
    "crying makeup", "smudged eyeliner", "dark circles", "tear-stained", "emotional"
  ],
  "shoegaze": [
    "blurry", "soft focus", "hazy", "dreamlike", "ethereal", "distortion", "dream pop",
    "ethereal glow", "diffused light", "luminescence", "shimmer", "transparent", "weightless",
    "film haze", "misty", "foggy", "smoky filters", "soft diffusion", "dreamy wash",
    "sunlight through blinds", "dappled light", "striped shadows", "morning glow", "intimate space",
    "dreamcore", "surreal", "subconscious", "floating", "non-linear", "mystical", "liminal",
    "pastel wash", "iridescent", "gradient", "color transitions", "aurora",
    "abstract patterns", "kaleidoscope", "swirling", "liquid light", "hypnotic", "geometric",
    "serene nature", "misty forest", "calm ocean", "clouds", "solitary figure", "tranquil"
  ],
  "hyperpop": [
    "neon", "fluorescent", "day-glo", "ultraviolet", "electric", "synthetic bright", "rave colors",
    "glitch art", "pixelation", "digital artifacts", "corrupted", "screen tear", "VHS tracking", "visual noise",
    "Y2K aesthetic", "early 2000s", "metallic", "bubble textures", "clunky tech", "shiny plastic", "retro-futuristic",
    "cybercore", "digital interface", "circuit", "holographic", "augmented reality", "virtual space", "AI",
    "digital overload", "information saturated", "pop-up", "internet culture", "maximalist", "sensory overload",
    "cartoon", "anime", "manga", "stylized gore", "hyper-real", "demented kawaii", "pop art",
    "chaotic", "disjointed", "non-linear", "fragmented", "collage",
    "toycore", "kawaii", "dolls", "plastic", "kitsch", "candy",
    "auto-tuned visuals", "distorted faces", "stretched", "synthetic skin", "unreal"
  ],
  "bedroom pop": [
    "sunset", "golden hour", "soft colors", "twilight", "dusk", "warm light", "magic hour",
    "soft lighting", "diffused", "window light", "candlelight", "gentle glow", "intimate", "cozy",
    "cozy space", "messy bed", "blankets", "pillows", "cluttered room", "personal sanctuary", "hygge",
    "rose-tinted", "warm filter", "sepia", "romanticized", "nostalgic", "dreamy haze", "blush tones",
    "dreamy aesthetic", "subtle blur", "out-of-focus", "ethereal", "gentle", "introspection", "daydreaming",
    "lo-fi intimacy", "vulnerable", "diary-like", "personal", "authentic", "raw emotion", "confessional",
    "natural textures", "soft fabrics", "wood", "plants", "books", "trinkets", "organic materials",
    "rainy window", "contemplative", "solitary", "quiet", "melancholy", "indoor comfort", "peaceful"
  ],
  "emo": [
    "crying makeup", "smudged eyeliner", "streaked mascara", "tear-stained", "vulnerable", "raw emotion",
    "black clothes", "skinny jeans", "band tee", "hoodies", "studded belt", "checkered", "punk accessories",
    "heartbreak", "broken hearts", "loneliness", "despair", "angst", "romantic tragedy", "sad vibes",
    "messy room", "cluttered", "disarray", "crumpled", "band posters", "dark lighting", "bedroom chaos",
    "melancholy", "sadness", "introspection", "solitude", "rainy day", "overcast", "gloomy", "wistful",
    "spiky hair", "side fringe", "straightened hair", "dyed hair", "untamed", "punk hair",
    "piercings", "tattoos", "choker", "wristbands", "fingerless gloves", "alternative accessories",
    "dark filters", "desaturated", "monochromatic", "high contrast", "gritty visuals", "bleak",
    "graveyard", "abandoned", "gothic", "run-down", "decay", "forgotten"
  ],
  "folk": [
    "cabincore", "rustic", "log cabin", "forest", "woodland", "hearth", "cozy interior", "cottagecore",
    "nature", "rolling hills", "dense forest", "calm river", "mountains", "meadows", "wildflowers", "natural beauty",
    "acoustic", "wooden guitar", "banjo", "fiddle", "harmonica", "porch pickin", "campfire", "unplugged",
    "wood textures", "rough wood", "pine", "birch", "natural grain", "organic materials", "timber", "earthy textures",
    "sunlit portraits", "golden hour", "backlit", "warm glow", "peaceful", "authentic smiles", "natural light",
    "earthy tones", "muted greens", "forest browns", "rust orange", "natural dyes", "organic palette", "autumnal",
    "handwoven", "knitted", "quilted", "patchwork", "natural fibers", "comfort fabrics", "handmade crafts",
    "gardening", "simple living", "rural", "traditional", "communal", "farm life", "homestead", "slow living",
    "vintage clothing", "embroidered", "apron", "practical attire", "timeless style", "heritage"
  ],
  "electronic": [
    "synthwave", "80s retro-futurism", "grid patterns", "glowing neon", "palm trees", "dusk", "arcade",
    "laser lights", "dynamic beams", "light shows", "strobe", "UV lights", "pulsating", "visualizer",
    "cyberpunk city", "rainy streets", "dystopian", "holographic", "tech dominance", "futuristic urban",
    "club lights", "disco balls", "fog machines", "flashing", "dark dance floor", "high energy", "rave",
    "abstract neon", "geometric", "light trails", "digital fractals", "fluid light", "glowing lines",
    "circuit board", "digital grids", "binary code", "glitch art", "technological abstract", "tech aesthetic",
    "robotic", "android", "human-machine", "bionic", "futuristic machinery", "cyborg", "AI art",
    "virtual reality", "simulated", "wireframe", "digital dreamscape", "augmented reality", "metaverse",
    "minimalist design", "sleek", "precise", "clean lines", "dark background"
  ],
  "jazz": [
    "vintage record", "vinyl", "turntable", "classic audio", "warm sound", "analog", "retro audio",
    "dim lights", "spotlights", "mood lighting", "intimate", "smoky room", "speakeasy", "low light",
    "blues aesthetic", "melancholy", "soulful", "raw emotion", "storytelling", "bluesy",
    "classic suits", "fedora", "bow tie", "crisp shirt", "tailored", "timeless fashion", "sophisticated",
    "urban chic", "city night", "rooftop bar", "lounge", "upscale venue", "city lights",
    "black and white", "sepia", "muted colors", "golden glow", "monochromatic", "timeless photo",
    "saxophone", "trumpet", "piano", "instrument focus", "musicality", "brass", "woodwind",
    "smoke", "cocktails", "martini", "whiskey", "bar scene", "smooth textures", "lounge atmosphere",
    "improvisation", "fluid movement", "spontaneous", "unpredictable", "freeform"
  ],
  "country": [
    "rustic barn", "farmland", "open fields", "dirt road", "wooden fence", "rural", "americana", "pastoral",
    "cowboy hat", "denim", "plaid", "leather boots", "buckle", "fringe", "western wear", "rodeo",
    "acoustic guitar", "banjo", "fiddle", "harmonica", "porch pickin", "campfire", "unplugged",
    "wood textures", "rough wood", "pine", "natural grain", "organic materials", "timber", "earthy textures",
    "sunset", "wide-open sky", "golden hour", "dusty light", "warm light", "country sunset",
    "small town", "community", "local diner", "main street", "friendly faces", "down-to-earth",
    "american flag", "pickup trucks", "rodeos", "line dancing", "western culture", "heritage",
    "natural textures", "earthy colors", "warm browns", "deep reds", "sky blues", "faded greens",
    "storytelling", "narrative", "slice-of-life", "sentimental", "authentic emotion"
  ],
  "r&b": [
    "smooth textures", "velvet", "silk", "soft lighting", "sensual", "luxurious", "intimate", "romantic",
    "dim lights", "candlelight", "spotlights", "moody glow", "urban nightlife", "lounge", "cocktail",
    "emotional", "vulnerable", "heartfelt", "passionate", "soulful", "raw emotion", "deep feelings",
    "sleek fashion", "tailored suits", "elegant dresses", "designer wear", "minimalist chic", "sophisticated",
    "city night", "rooftop view", "upscale apartment", "exclusive venue", "urban romance", "city lights",
    "monochromatic", "deep jewel tones", "gold accents", "warm palette", "rich colors",
    "close-up portraits", "intimate moments", "candid interactions", "couple", "sensual poses",
    "vintage mic", "analog gear", "retro audio", "timeless sound", "studio vibes",
    "smoke", "drinks", "vinyl", "relaxed", "smooth movement", "effortless"
  ],
  "reggae": [
    "rasta colors", "african patterns", "cultural pride", "vibrant hues", "earthy tones",
    "beach", "tropical", "palm trees", "ocean", "sunny", "island", "caribbean", "paradise",
    "dreadlocks", "natural hair", "headwraps", "flowing clothes", "natural fibers", "bohemian",
    "irie vibes", "peaceful", "relaxed", "smiles", "unity", "community", "positive energy",
    "ganja", "smoke", "meditative", "spiritual", "natural elements", "organic",
    "hand drums", "percussion", "bass", "rhythm", "live music", "jam session", "roots music",
    "vibrant patterns", "geometric designs", "tie-dye", "colorful prints", "tribal",
    "jamaican landscape", "waterfalls", "lush green", "blue mountains", "rural charm",
    "conscious living", "natural food", "organic produce", "simple lifestyle", "harmony"
  ],
  "blues": [
    "dim light", "smoky club", "juke joint", "backroom", "shadowy", "intimate stage", "low light",
    "gritty textures", "worn wood", "rust", "peeling paint", "aged surfaces", "decay", "distressed",
    "guitar focus", "slide guitar", "harmonica", "upright bass", "raw instruments", "soulful play",
    "melancholy", "sadness", "burdened", "pain", "resilience", "somber", "heartache",
    "rural south", "cotton fields", "dilapidated", "dusty road", "porch", "historical",
    "black and white", "sepia", "desaturated", "muted tones", "high contrast", "moody palette",
    "vintage mic", "old amps", "classic instruments", "timeless music", "retro gear",
    "storytelling", "narrative", "struggle", "human experience", "real life",
    "cigarette smoke", "whiskey", "solitary", "contemplative"
  ],
  "classical": [
    "concert hall", "ornate theatre", "opera house", "symphony", "majestic architecture", "grand",
    "formal attire", "tuxedos", "evening gowns", "black tie", "elegant", "sophisticated", "regal",
    "orchestra", "violin", "cello", "piano", "woodwinds", "brass", "precise", "chamber music",
    "classic art", "renaissance", "baroque", "neoclassical", "mythology", "fine art", "masterpiece",
    "rich textures", "velvet", "silk", "jewel tones", "gold accents", "luxurious", "sumptuous", "gilded",
    "dramatic lighting", "spotlight", "chiaroscuro", "shadow play", "moody light", "theatrical",
    "historic", "palace", "manor", "museum", "library", "timeless elegance", "period drama",
    "focused intensity", "concentration", "expressive", "precision", "dedicated", "masterful",
    "abstract beauty", "complex patterns", "mathematical", "architectural", "structured"
  ],
  "edm": [
    "rave", "crowd", "festival", "laser show", "pyrotechnics", "confetti", "fog", "dance party",
    "vibrant neon", "UV reactive", "glow sticks", "light-up", "day-glo", "electric colors", "fluorescent",
    "psychedelic", "kaleidoscope", "fractal", "trippy", "immersive", "visual illusions", "mind bending",
    "cybernetic", "LED clothing", "robotics", "digital avatar", "techwear", "futuristic gear", "augmented reality",
    "high energy", "dancing", "jumping", "euphoric", "collective", "dance floor", "party", "unleashed energy",
    "futuristic city", "spaceships", "alien landscape", "interstellar", "sci-fi", "cosmic", "cyberpunk city",
    "geometric light", "tunnel", "warp speed", "infinity mirror", "repetitive patterns", "hypnotic",
    "abstract forms", "liquid light", "particle", "digital art", "synthesized visuals", "motion graphics",
    "unity", "connection", "peace", "love", "ecstasy", "transcendent", "communal"
  ],
  "gospel": [
    "church", "altar", "stained glass", "congregation", "choir", "pulpit", "sacred space", "worship",
    "joyful", "uplifted hands", "exuberant", "spiritual", "emotional release", "hope", "faith", "praise",
    "community", "fellowship", "shared worship", "intergenerational", "collective", "church family",
    "bright light", "warm glow", "sunbeams", "radiant", "heavenly light", "divine light", "pure light",
    "formal attire", "suits", "dresses", "hats", "clean fashion", "sunday best", "modest",
    "hand clapping", "foot stomping", "swaying", "passionate", "energetic", "soulful", "rhythmic",
    "choir", "group harmonies", "powerful vocals", "unison", "vocal ensemble", "harmonious",
    "biblical", "crosses", "dove", "scripture", "faith symbols", "divine inspiration",
    "authentic emotion", "unfiltered joy", "gratitude", "spiritual awakening", "heartfelt"
  ],
  "k-pop": [
    "choreography", "synchronized dance", "dynamic stage", "group precision", "idol dance", "performance",
    "cutting-edge fashion", "designer", "androgynous", "bold colors", "futuristic textiles", "multiple outfits",
    "high-concept video", "narrative", "stunning sets", "CGI", "cinematic", "visual masterpiece",
    "bright colors", "vivid", "pastel gradient", "neon accents", "color blocking", "vibrant palette",
    "glamorous", "flawless makeup", "intricate hair", "sparkling", "polished", "idol beauty", "glitter",
    "futuristic urban", "digital city", "tech interface", "LED screens", "sleek architecture", "cyber city",
    "group dynamics", "individual spotlight", "team synergy", "friendship", "aspirational", "squad goals",
    "fan interaction", "light sticks", "concert arena", "energetic crowds", "global", "fandom",
    "symbolic", "easter eggs", "visual metaphors", "complex narrative", "deep meaning",
    "luxury brand", "product placement", "consumerism"
  ],
  "j-rock": [
    "anime", "manga", "stylized characters", "expressive", "action poses", "graphic novel", "cartoon",
    "visual kei", "androgynous", "elaborate hair", "gothic", "punk", "victorian", "harajuku", "cosplay",
    "dark vibrant colors", "deep reds", "purples", "blacks", "bright accents", "high contrast", "moody light",
    "theatrical", "dramatic", "emotional intensity", "storytelling", "hyper-expressive", "live show",
    "urban decay", "abandoned", "cyberpunk", "gritty aesthetic", "ruined city", "industrial",
    "symbolic imagery", "roses", "thorns", "crosses", "chains", "fantasy", "mythological", "occult",
    "loud", "energetic", "shredding guitar", "powerful drums", "vocalist focus", "intense music",
    "distorted visuals", "glitch", "light streaks", "motion blur", "visual effects", "abstract distortion",
    "individualistic", "unique identity", "rebellion", "self-expression", "non-conformist"
  ],
  "lo-fi hip hop": [
    "chill", "relaxed", "peaceful", "minimal", "calm", "serene", "study vibes", "cozy", "mellow",
    "warm colors", "muted tones", "browns", "beiges", "desaturated", "cozy light", "golden hour",
    "rainy window", "coffee", "books", "vinyl", "study setting", "indoor comfort", "hygge",
    "anime loops", "aesthetic GIFs", "repeating animation", "cinemagraphs", "animated", "retro anime",
    "city at night", "urban solitude", "quiet city", "night city", "blurred lights",
    "vintage electronics", "retro tech", "analog", "old school tech", "classic electronics",
    "film grain", "light leaks", "VHS", "imperfect", "soft focus", "dreamy blur",
    "pets", "plants", "indoor greenery", "cozy pets", "houseplants",
    "empty room", "soft textures", "blankets", "comfortable", "solitude", "minimalist living"
  ],
  "trap": [
    "dark", "gritty light", "low-key", "shadowy", "intense contrast", "moody", "underground", "ominous",
    "red neon", "blue neon", "harsh neon", "laser", "smoky", "club haze", "mysterious light",
    "luxury cars", "expensive watch", "diamond chain", "designer", "cash money", "bling", "supercars",
    "urban decay", "abandoned warehouse", "grimy street", "industrial", "concrete", "chain link",
    "street cred", "tough", "unapologetic", "criminal", "hustle", "power",
    "pyrotechnics", "fire", "explosions", "smoke bombs", "dynamic energy", "impactful",
    "money counting", "stacks of cash", "drug culture", "underworld", "dark opulence",
    "dramatic close-up", "intense stare", "serious expression", "powerful gaze", "piercing eyes",
    "fast cuts", "slow motion", "aggressive edit", "digital distortion", "glitch", "shaky cam"
  ],
  "punk": [
    "DIY", "hand-drawn", "photocopy", "zine", "cut and paste", "raw art", "homemade", "unpolished",
    "gritty urban", "back alley", "underpass", "graffiti", "run-down", "city street", "urban decay",
    "rebel fashion", "ripped clothes", "safety pins", "patches", "studded jacket", "mohawk", "spiked hair",
    "black and white", "high contrast", "harsh light", "desaturated", "monochromatic", "raw visuals",
    "energetic", "stage diving", "mosh pit", "crowd chaos", "raw aggression", "unleashed energy", "live show",
    "political", "protest", "anti-establishment", "activism", "social commentary", "revolt",
    "distorted visuals", "grainy film", "blurry motion", "chaotic", "visual noise", "unsettling",
    "dive bar", "underground venue", "sweaty club", "grimy interior", "backstage", "authentic scene",
    "youth subculture", "rebellion", "angst", "disaffected", "counterculture", "outsider art"
  ],
  "disco": [
    "glamorous", "sequins", "glitter", "bell bottoms", "platform shoes", "satin", "metallic", "sparkle",
    "vibrant light", "disco ball", "strobe", "colorful", "dance floor", "pulsating light", "party lights",
    "dance", "choreographed", "energetic", "groove", "rhythm", "nightclub", "boogie",
    "retro 70s", "vintage car", "retro interior", "groovy patterns", "psychedelic", "throwback", "nostalgic",
    "sparkly", "reflective", "mirror", "shiny", "iridescent", "luminous", "bling",
    "nightlife", "packed dance floor", "club culture", "late night", "social", "fun", "celebration",
    "bold patterns", "geometric prints", "abstract designs", "swirling", "optical", "vibrant prints",
    "roller skating", "roller disco", "skate rink", "leisure", "fun and games",
    "joyful", "smiling", "euphoric", "carefree", "happiness", "good vibes"
  ],
  "funk": [
    "groovy", "retro patterns", "geometric", "swirling", "psychedelic", "vibrant prints", "abstract art",
    "colorful", "bright", "saturated", "earthy tones", "warm colors", "bold color", "pop art",
    "retro fashion", "bell bottoms", "afro", "platform shoes", "velvet suits", "silk shirts", "soul fashion",
    "energetic", "dynamic", "dance moves", "bass guitar", "horns", "expressive", "live music", "jam session",
    "soulful", "deep emotion", "passionate", "vocal runs", "heartfelt",
    "urban street", "block party", "community", "street art", "city life",
    "vintage mic", "analog gear", "old instruments", "retro audio", "authentic sound",
    "playful", "humorous", "lighthearted", "joyful", "upbeat",
    "smooth textures", "velvet", "satin", "polished", "reflective", "sleek"
  ],
  "blues rock": [
    "raw guitar", "electric guitar", "slide guitar", "overdriven amps", "gritty tone", "guitar hero",
    "gritty textures", "worn leather", "distressed denim", "aged wood", "rust", "rough edges", "authentic",
    "american roots", "southern landscape", "old diner", "roadside motel", "desert road", "americana",
    "bar scene", "smoky club", "dive bar", "intimate venue", "stage performance", "live music", "whiskey bar",
    "black and white", "sepia", "desaturated", "high contrast", "dramatic shadows", "timeless visuals",
    "authentic expressions", "soulful", "passionate", "raw emotion", "unfiltered", "heartfelt",
    "vintage cars", "open road", "road trip", "freedom", "muscle car",
    "simple composition", "focused musician", "uncluttered", "direct visuals", "unpretentious",
    "storytelling", "narrative", "struggle", "human experience", "real life"
  ],
  "psychedelic rock": [
    "trippy", "kaleidoscope", "swirling", "liquid light", "fractal", "hallucinatory", "mind bending", "surreal",
    "colorful", "rainbow", "acid colors", "fluorescent", "saturated", "electric", "bold",
    "surreal landscape", "dreamscape", "abstract environment", "otherworldly", "fantasy", "unreal", "ethereal",
    "abstract art", "fluid shapes", "blurred", "organic patterns", "geometric abstract", "op art",
    "counter-culture", "tie-dye", "bell bottoms", "paisley", "hippie", "bohemian", "vintage fashion",
    "vibrant nature", "distorted forest", "colorful flowers", "unnatural colors",
    "light shows", "strobe", "diffused light", "color washes", "atmospheric light",
    "vintage posters", "hand-drawn type", "retro graphics", "album art", "iconic",
    "spiritual", "cosmic", "universal patterns", "meditative", "transcendence"
  ],
  "ambient": [
    "minimalist", "clean lines", "sparse", "empty space", "simplicity", "uncluttered", "zen", "serene",
    "atmospheric light", "soft glow", "diffused light", "subtle gradient", "hazy", "moody", "ethereal light",
    "serene landscape", "misty forest", "calm ocean", "clouds", "vast open", "tranquil nature", "peaceful",
    "abstract forms", "fluid shapes", "blurred edges", "gentle", "subtle movement", "ethereal art",
    "muted colors", "desaturated", "monochromatic", "earthy tones", "calming", "soft focus", "dreamy palette",
    "contemplative", "solitude", "introspection", "peaceful", "meditative", "mindfulness", "calmness",
    "natural textures", "flowing fabrics", "smooth surfaces", "organic materials", "gentle textures",
    "slow motion", "long exposure", "time lapse", "fluid movement", "hypnotic",
    "vastness", "open space", "horizon", "distant view", "expansive", "solitary"
  ],
  "techno": [
    "industrial", "concrete", "metal", "dark warehouse", "gritty urban", "raw materials", "factory",
    "repetitive patterns", "geometric grid", "pulsating light", "strobe", "hypnotic", "minimalist patterns",
    "dark club", "underground", "shadowy", "intense light", "fog", "laser beams", "rave", "nightlife",
    "minimalist design", "stark", "black and white", "monochromatic", "high contrast", "stripped down",
    "cyberpunk", "dystopian", "tech decay", "machine aesthetic", "digital grit", "circuitry",
    "abstract forms", "angular", "sharp", "geometric abstract", "fractals", "mechanical",
    "focused intensity", "rhythm", "trance", "immersive", "unrelenting", "mesmerizing",
    "smoke", "mirrors", "illusion", "disorientation", "sensory",
    "underground culture", "rebellion", "anti-commercial", "authentic electronic", "raw energy"
  ],
  "house": [
    "uplifting", "joyful", "energetic", "euphoric", "celebration", "happiness", "good vibes", "positive",
    "vibrant dance floor", "colorful light", "disco ball", "club", "party", "nightlife", "dance",
    "soulful", "warm colors", "golden hour", "amber glow", "intimate light", "smooth",
    "groovy fashion", "retro 80s", "90s fashion", "casual chic", "comfortable", "expressive",
    "community", "crowd", "shared experience", "unity", "friendship", "togetherness",
    "city night", "urban skyline", "rooftop party", "open air", "city lights", "urban celebration",
    "abstract patterns", "liquid light", "color wash", "subtle gradient", "rhythmic", "visualizer",
    "vocal focus", "soulful singer", "expressive faces", "microphone", "passionate", "diva",
    "classic club", "turntables", "DJ booth", "sound system", "vinyl", "analog gear"
  ],
  "afrobeats": [
    "vibrant colors", "bold patterns", "african prints", "rich textiles", "colorful fashion", "traditional",
    "rhythmic", "dance", "energetic", "choreography", "body expression", "fluid motion", "celebratory", "groove",
    "sunny", "tropical", "lush green", "beach", "natural light", "bright daylight", "warm climate",
    "community", "street party", "festival", "cultural", "unity", "joyful crowd", "family", "friends",
    "urban african", "bustling market", "street life", "modern african", "cityscape", "dynamic urban",
    "traditional instruments", "percussion", "drums", "shakers", "horns", "live music", "authentic sound",
    "storytelling", "narrative", "daily life", "aspirational", "cultural pride",
    "gold accents", "natural jewelry", "beads", "headwraps", "statement accessories", "ethnic jewelry",
    "authentic expressions", "smiling", "joyful", "confident", "positive energy", "happiness"
  ],
  "latin pop / reggaeton": [
    "energetic dance", "salsa", "reggaeton choreography", "hip movement", "sensual", "party", "club dance",
    "vibrant colors", "tropical hues", "neon accents", "bright fashion", "colorful outfits", "summer",
    "tropical landscape", "beach party", "palm trees", "ocean", "sunny resorts", "island", "paradise",
    "urban street", "city nightlife", "block party", "street art", "city life", "urban celebration",
    "sensual expressions", "flirtatious", "confident", "passionate", "romantic", "sultry", "desire",
    "luxury", "flashy cars", "designer", "aspirational", "glamorous", "high end",
    "group gathering", "friends dancing", "party crowd", "social", "fun", "celebration",
    "body positive", "confident posture", "curves", "expressive movement", "uninhibited",
    "music video", "fast cuts", "dynamic camera", "visual effects", "cinematic"
  ]
};